export const LOCATION_CHANGE = 'LOCATION CHANGE';

export const LOGIN_SUBMIT = 'LOGIN SUBMIT';
export const LOGIN_RESPONSE = 'LOGIN RESPONSE';
export const LOGIN_ERROR = 'LOGIN ERROR';
export const LOGIN_CLEAR_ERROR = 'LOGIN CLEAR ERROR';

export const MODEL_INITIALIZE = 'MODEL INITIALIZE';
export const MODEL_UNINITIALIZE = 'MODEL UNINITIALIZE';

export const CHAT_JOIN = 'CHAT JOIN';
export const CHAT_LEAVE = 'CHAT LEAVE';

export const THEME_JOIN = 'THEME JOIN';
export const THEME_LEAVE = 'THEME LEAVE';

export const NETWORK_ERROR = 'NETWORK ERROR';

export const CONSOLE_LOG = 'CONSOLE LOG';
export const CONSOLE_LOG_HIDE = 'CONSOLE LOG HIDE';

export const TOGGLE_HEADER = 'TOGGLE HEADER';
export const TOGGLE_NAV = 'TOGGLE NAV';

